language: python
addons:
  apt:
    packages:
    - zlib1g-dev
    - libncurses5-dev
    - libncursesw5-dev
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - SAMTOOLS_VERSION=1.3
  - SAMTOOLS_VERSION=1.3.1
  - SAMTOOLS_VERSION=1.4
  - SAMTOOLS_VERSION=1.4.1
  - SAMTOOLS_VERSION=1.5
  - SAMTOOLS_VERSION=1.6
sudo: false
install:
  - "source ./install_dependencies.sh"
script:
  - "python setup.py test"
